
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOSE COMMA EQUALS INTEGER IP LPAREN NEWLINE OPEN PING RECEIVE RPAREN SEMI SEND STRING WORD\n    function : OPEN LPAREN IP RPAREN\n    \n    function : CLOSE LPAREN RPAREN\n    \n    function : PING LPAREN RPAREN\n             | PING LPAREN IP RPAREN\n    \n    function : SEND LPAREN data RPAREN\n    \n    data : STRING\n         | WORD\n         | INTEGER\n    '
    
_lr_action_items = {'WORD':([7,],[14,]),'RPAREN':([6,8,11,12,13,14,15,17,],[10,16,18,-6,-8,-7,19,20,]),'STRING':([7,],[12,]),'IP':([6,9,],[11,17,]),'PING':([0,],[2,]),'SEND':([0,],[3,]),'LPAREN':([2,3,4,5,],[6,7,8,9,]),'INTEGER':([7,],[13,]),'CLOSE':([0,],[4,]),'OPEN':([0,],[5,]),'$end':([1,10,16,18,19,20,],[0,-3,-2,-4,-5,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'function':([0,],[1,]),'data':([7,],[15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> function","S'",1,None,None,None),
  ('function -> OPEN LPAREN IP RPAREN','function',4,'p_function_open','ConvoParser.py',8),
  ('function -> CLOSE LPAREN RPAREN','function',3,'p_function_close','ConvoParser.py',14),
  ('function -> PING LPAREN RPAREN','function',3,'p_function_ping','ConvoParser.py',20),
  ('function -> PING LPAREN IP RPAREN','function',4,'p_function_ping','ConvoParser.py',21),
  ('function -> SEND LPAREN data RPAREN','function',4,'p_function_send','ConvoParser.py',27),
  ('data -> STRING','data',1,'p_data','ConvoParser.py',33),
  ('data -> WORD','data',1,'p_data','ConvoParser.py',34),
  ('data -> INTEGER','data',1,'p_data','ConvoParser.py',35),
]
